CREATE TYPE public.app_role AS ENUM ('admin');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_role ON public.user_roles FOR SELECT TO authenticated USING (user_id=auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE TABLE public.evolution_photos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), path text NOT NULL UNIQUE, url text NOT NULL, caption text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.evolution_photos TO anon; GRANT SELECT,INSERT,UPDATE,DELETE ON public.evolution_photos TO authenticated; GRANT ALL ON public.evolution_photos TO service_role;
ALTER TABLE public.evolution_photos ENABLE ROW LEVEL SECURITY;
CREATE POLICY public_photos ON public.evolution_photos FOR SELECT TO anon,authenticated USING(true);
CREATE POLICY admin_photos ON public.evolution_photos FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE TABLE public.leads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK(char_length(name) BETWEEN 2 AND 100), age integer NOT NULL CHECK(age BETWEEN 1 AND 120), location text NOT NULL CHECK(char_length(location) BETWEEN 2 AND 150), experience text NOT NULL CHECK(experience IN ('Iniciante','Intermediária','Avançada')), whatsapp text NOT NULL CHECK(whatsapp ~ '^[0-9]{10,11}$'), created_at timestamptz NOT NULL DEFAULT now());
GRANT INSERT ON public.leads TO anon; GRANT SELECT,INSERT ON public.leads TO authenticated; GRANT ALL ON public.leads TO service_role;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY submit_lead ON public.leads FOR INSERT TO anon,authenticated WITH CHECK(true);
CREATE POLICY admin_leads ON public.leads FOR SELECT TO authenticated USING(public.has_role(auth.uid(),'admin'));
CREATE POLICY admin_storage_insert ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id='evolucao' AND public.has_role(auth.uid(),'admin'));
CREATE POLICY admin_storage_delete ON storage.objects FOR DELETE TO authenticated USING(bucket_id='evolucao' AND public.has_role(auth.uid(),'admin'));
CREATE POLICY storage_read ON storage.objects FOR SELECT TO anon,authenticated USING(bucket_id='evolucao');
ALTER PUBLICATION supabase_realtime ADD TABLE public.evolution_photos;